# lib\tests\test_exceptions.py